# Generated by Django 2.1.5 on 2019-03-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_trusty',
            field=models.BooleanField(default=False, help_text='Indica que o email do usuário foi verificado.', verbose_name='verificado'),
        ),
    ]
