# Generated by Django 2.2.1 on 2019-08-10 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egresso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossivelResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Possível Resposta',
                'verbose_name_plural': 'Possíveis Respostas',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('habilitar_opcao_outro', models.BooleanField(default=False, help_text='Permite que o egresso forneça uma outra resposta', verbose_name='Permitir outra resposta')),
                ('possiveis_respostas', models.ManyToManyField(to='questionario.PossivelResposta')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
            },
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anos_corridos', models.IntegerField(unique=True, verbose_name='Responder depois de quantos após formar')),
                ('questoes', models.ManyToManyField(to='questionario.Questao')),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
            },
        ),
        migrations.CreateModel(
            name='RespostaQuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=255)),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egresso.Formacao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionario.Questao')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionario.Questionario')),
            ],
            options={
                'verbose_name': 'Resposta Questionário',
                'verbose_name_plural': 'Respostas Questionário',
            },
        ),
    ]
