# Generated by Django 2.2.1 on 2019-08-08 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('egresso', '0006_auto_20190808_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=255)),
                ('habilitar_opcao_outro', models.BooleanField(default=False, help_text='Permite que o egresso forneça uma outra opção', verbose_name='Permitir outra opção')),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anos_corridos', models.IntegerField()),
                ('questoes', models.ManyToManyField(to='questionario.Questao')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaQuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=255)),
                ('formacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egresso.Formacao')),
                ('questao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='questionario.Questao')),
                ('questionario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='questionario.Questionario')),
            ],
        ),
        migrations.CreateModel(
            name='PossivelResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=255)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionario.Questao')),
            ],
        ),
    ]
