# Generated by Django 2.2.1 on 2019-08-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='possivelresposta',
            options={'verbose_name': 'Possível Resposta', 'verbose_name_plural': 'Possíveis Respostas'},
        ),
        migrations.AlterModelOptions(
            name='questao',
            options={'verbose_name': 'Questão', 'verbose_name_plural': 'Questões'},
        ),
        migrations.AlterModelOptions(
            name='questionario',
            options={'verbose_name': 'Questionário', 'verbose_name_plural': 'Questionários'},
        ),
        migrations.AlterModelOptions(
            name='respostaquestionario',
            options={'verbose_name': 'Resposta Questionário', 'verbose_name_plural': 'Respostas Questionário'},
        ),
        migrations.RemoveField(
            model_name='possivelresposta',
            name='questao',
        ),
        migrations.AddField(
            model_name='possivelresposta',
            name='questao',
            field=models.ManyToManyField(to='questionario.Questao'),
        ),
    ]
