# Generated by Django 2.2.1 on 2019-08-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0002_auto_20190808_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possivelresposta',
            name='questao',
        ),
        migrations.AddField(
            model_name='possivelresposta',
            name='questao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='questionario.Questao'),
            preserve_default=False,
        ),
    ]
