# Generated by Django 2.2.1 on 2019-08-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0003_auto_20190808_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possivelresposta',
            name='questao',
        ),
        migrations.AddField(
            model_name='questao',
            name='possiveis_respostas',
            field=models.ManyToManyField(to='questionario.PossivelResposta'),
        ),
    ]
