# Generated by Django 2.2.1 on 2019-06-21 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOportunidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tipo de Oportunidade',
                'verbose_name_plural': 'Tipos de oportunidade',
            },
        ),
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('horas_semana', models.IntegerField()),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=2)),
                ('curso_objetivo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.Curso')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oportunidade.TipoOportunidade')),
            ],
        ),
    ]
