# Generated by Django 2.2.1 on 2019-08-07 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('oportunidade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunidade',
            name='area_necessaria',
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='area_necessaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.AreaAtuacao'),
        ),
    ]
