# Generated by Django 2.1.5 on 2019-03-06 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidade',
            name='cidade',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='estado',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
