# Generated by Django 2.2.1 on 2019-06-21 21:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('identidade', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateField(default=datetime.datetime(2001, 6, 21, 21, 39, 55, 895289))),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('carteira_motorista', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Dados Pessoais',
                'verbose_name_plural': 'Dados Pessoais',
            },
        ),
        migrations.CreateModel(
            name='Egresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('is_aluno', models.BooleanField(default=False, help_text='Designado quando o usuário cadastrado ainda é aluno.', verbose_name='aluno status')),
                ('raio_atuacao_max', models.IntegerField(default=0, help_text='Raio de distância (Km) para encontrar oportunidades.')),
                ('dados', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='egresso.DadosPessoais')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
                ('rua', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civís',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
            },
        ),
        migrations.CreateModel(
            name='PerfilSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_linkedin', models.CharField(blank=True, max_length=250, null=True)),
                ('link_lattes', models.CharField(blank=True, max_length=250, null=True)),
                ('link_github', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Perfil Sites',
                'verbose_name_plural': 'Perfil Sites',
            },
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_inicio', models.IntegerField(default=0)),
                ('ano_termino', models.IntegerField(default=0)),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curso.Curso')),
                ('egresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egresso.Egresso')),
            ],
            options={
                'verbose_name': 'Formação Acadêmica',
                'verbose_name_plural': 'Formações Acadêmicas',
            },
        ),
        migrations.AddField(
            model_name='egresso',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='egresso.Endereco'),
        ),
        migrations.AddField(
            model_name='egresso',
            name='perfil_sites',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='egresso.PerfilSites'),
        ),
        migrations.AddField(
            model_name='egresso',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='escolaridade_mae',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escolaridade_mae_set', to='egresso.Escolaridade'),
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='escolaridade_pai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escolaridade_pai_set', to='egresso.Escolaridade'),
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='estado_civil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='egresso.EstadoCivil'),
        ),
        migrations.AddField(
            model_name='dadospessoais',
            name='genero',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='egresso.Genero'),
        ),
    ]
