# Generated by Django 2.2.1 on 2019-06-02 19:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Egresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(default=datetime.datetime(2001, 6, 2, 19, 10, 52, 854537))),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('identidade', models.CharField(blank=True, max_length=15, null=True)),
                ('link_linkedin', models.CharField(blank=True, max_length=250, null=True)),
                ('link_lattes', models.CharField(blank=True, max_length=250, null=True)),
                ('link_github', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=15, null=True)),
                ('rua', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=20, null=True)),
                ('bairro', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=60)),
                ('estado', models.CharField(max_length=2)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Formacao_Academica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_inicio', models.IntegerField(default=0)),
                ('ano_termino', models.IntegerField(default=0)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.Area_Curso')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.Curso')),
                ('egresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egresso.Egresso')),
                ('nivel_formacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='curso.Nivel_Curso')),
            ],
            options={
                'verbose_name': 'Formação Acadêmica',
                'verbose_name_plural': 'Formações Acadêmicas',
            },
        ),
        migrations.AddField(
            model_name='egresso',
            name='endereco',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='egresso.Endereco'),
        ),
        migrations.AddField(
            model_name='egresso',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
