# Generated by Django 2.2.1 on 2019-06-03 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresso',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2001, 6, 3, 14, 51, 22, 36891)),
        ),
    ]
