# Generated by Django 2.1.5 on 2019-02-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresso',
            name='nome_completo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
