# Generated by Django 2.1.5 on 2019-02-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresso', '0002_egresso_nome_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresso',
            name='link_lattes',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='egresso',
            name='link_likedin',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
