# Generated by Django 2.1.5 on 2019-04-04 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresso', '0002_auto_20190404_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresso',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2001, 4, 4, 13, 12, 29, 531832)),
        ),
    ]
