# Generated by Django 2.2.1 on 2019-06-22 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresso', '0002_auto_20190621_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2001, 6, 22, 21, 10, 42, 581403)),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='escolaridade_mae',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='escolaridade_pai',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='egresso',
            name='matricula',
            field=models.CharField(max_length=30),
        ),
    ]
