# Generated by Django 2.2.1 on 2019-06-22 21:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresso', '0003_auto_20190622_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2001, 6, 22, 21, 16, 51, 740402)),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='estado_civil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='egresso.EstadoCivil'),
        ),
        migrations.AlterField(
            model_name='dadospessoais',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='egresso.Genero'),
        ),
    ]
