# Generated by Django 2.1.5 on 2019-03-10 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresso', '0004_auto_20190310_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresso',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2001, 3, 10, 21, 59, 40, 551936)),
        ),
    ]
