# Generated by Django 2.2.1 on 2019-07-15 21:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('egresso', '0004_auto_20190622_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2001, 7, 15, 21, 30, 25, 960286)),
        ),
        migrations.AlterField(
            model_name='formacao',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Curso'),
        ),
    ]
