# Generated by Django 2.2.1 on 2019-08-09 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresso', '0009_auto_20190808_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='data_nascimento',
            field=models.DateField(default=datetime.datetime(2001, 8, 9, 18, 3, 58, 119216)),
        ),
        migrations.AlterField(
            model_name='formacao',
            name='ano_termino',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
